global_options:
  freezed:
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator

targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: assets/i18n
          input_file_pattern: .json
          output_directory: lib/generated
          output_file_name: translations.g.dart
          output_format: single_file
          locale_handling: true
          translate_var: t
          enum_name: AppLocale
          translation_class_visibility: private
          key_case: camel
          param_case: camel
          string_interpolation: braces
          flat_map: true
          timestamp: true
          interfaces:
            TaskData: tasks.tasks.*
          maps:
            - general.theme.name
            - models.rarity.values
